version: "2"
services:
  neuroscout:
    restart: always
    build: ./neuroscout
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - migrations:/migrations
      - ./neuroscout/:/neuroscout
      - $DATASET_DIR:/datasets
      - $KEY_DIR:/keys
      - file-data:/file-data
    command: /usr/local/bin/gunicorn -w 2 -b :8000 core:app --log-level debug
    env_file:
      - .env
      - .pliersenv

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    volumes_from:
      - neuroscout
    links:
      - neuroscout:neuroscout

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: ./postgres
    volumes_from:
      - data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=neuroscout

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - "API_URL=/swagger"
    ports:
      - '8080:8080'

  redis:
    image: redis

  worker:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    entrypoint: celery -A tasks worker --loglevel=info
    volumes:
      - file-data:/file-data
      - $DATASET_DIR:/datasets
      - ./neuroscout/:/neuroscout
      - ./celery_worker/:/celery_worker

    env_file: .env

  monitor:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
    env_file: .env

volumes:
  migrations:
  file-data:
