version: "2"
services:
  neuroscout:
    restart: always
    build: ./neuroscout
    expose:
      - "8000"
    volumes:
      - ./postgres/migrations:/migrations
      - ./neuroscout/:/neuroscout
      - ${DATASET_DIR}:/datasets
      - ${KEY_DIR}:/keys
      - ${FILE_DATA}:/file-data
    command: /usr/local/bin/gunicorn -w 2 -b :8000 core:app --log-level debug --timeout 120
    env_file:
      - .env
      - .pliersenv

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    volumes_from:
      - neuroscout

  postgres:
    restart: always
    build: ./postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=neuroscout
    env_file:
      - .pliersenv

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - "API_URL=https://alpha.neuroscout.org/swagger/"
    expose:
      - '8080'

  redis:
    image: redis

  worker:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    entrypoint: celery -A tasks worker --loglevel=info
    volumes:
      - ${FILE_DATA}:/file-data
      - ${DATASET_DIR}:/datasets
      - ./neuroscout/:/neuroscout
      - ./celery_worker/:/celery_worker
    env_file: .env

  monitor:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
    env_file: .env

volumes:
  postgres-data:
  certs:
  certs-data:
